# Generated by Django 2.1.7 on 2019-03-31 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
